# Generated by Django 5.0.2 on 2024-03-29 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название цвета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название категории')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярен?')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит?')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый?')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен на сайте?')),
                ('icon', models.FileField(blank=True, null=True, upload_to='media/category/icon/', verbose_name='Категория значка')),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/category/logo/', verbose_name='Категория логотипа')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productcategories')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.productcategories',),
        ),
        migrations.CreateModel(
            name='TertiaryCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Третичная категория',
                'verbose_name_plural': 'Третичные категории',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.productcategories',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название продукта')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное Название продукта')),
                ('brand', models.CharField(blank=True, max_length=155, null=True, verbose_name='Бренд')),
                ('article', models.CharField(blank=True, max_length=155, null=True, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(blank=True, choices=[('RUB', 'Rub'), ('USD', 'Usd')], default='RUB', max_length=10, null=True, verbose_name='Цена валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('attributes', models.JSONField(blank=True, null=True, verbose_name='Атрибуты')),
                ('included_branding', models.JSONField(blank=True, null=True, verbose_name='Включенный брендинг')),
                ('discount_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена со скидкой')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярен?')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит?')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый?')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Данные опубликованы')),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSubCategoryID', to='product.productcategories', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукт',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('big', models.ImageField(blank=True, null=True, upload_to='product/images/big', verbose_name='Большой Изображений')),
                ('big_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL большого изображения')),
                ('small', models.ImageField(blank=True, null=True, upload_to='product/images/small', verbose_name='Маленький Изображений')),
                ('small_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL маленького изображения')),
                ('superbig', models.ImageField(blank=True, null=True, upload_to='product/images/superbig', verbose_name='Супербольшой Изображений')),
                ('superbig_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL супербольшого изображения')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product/images/thumbnail', verbose_name='Миниатюра Изображений')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL миниатюры изображения')),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productID', to='product.products', verbose_name='Код товара')),
            ],
            options={
                'verbose_name': 'Изображения продукта',
                'verbose_name_plural': 'Изображения продукта',
                'db_table': 'product_images',
            },
        ),
    ]
