# Generated by Django 5.0.2 on 2024-02-29 17:35

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of category')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icon_category', verbose_name='Icon Category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of sub category')),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategoryID', to='product.productcategories')),
            ],
            options={
                'verbose_name': 'Product Sub Category',
                'verbose_name_plural': 'Product Sub Categories',
                'db_table': 'product_sub_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of product')),
                ('content', ckeditor.fields.RichTextField()),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Price')),
                ('price_type', models.CharField(blank=True, choices=[('RUB', 'Rub'), ('USD', 'Usd')], default='RUB', max_length=10, null=True, verbose_name='Type of price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pro_image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSubCategoryID', to='product.productsubcategories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
