# Generated by Django 5.0.2 on 2024-02-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSubCategoryID', to='product.productcategories'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productcategories', verbose_name='CategoryID'),
        ),
        migrations.DeleteModel(
            name='ProductSubCategories',
        ),
    ]
