# Generated by Django 5.0.2 on 2024-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='products',
            name='content',
        ),
        migrations.RemoveField(
            model_name='products',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.RemoveField(
            model_name='products',
            name='package_dimensions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='package_quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='package_wight',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступен на сайте?'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='big',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/big', verbose_name='Большой Изображений'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/small', verbose_name='Маленький Изображений'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='superbig',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/superbig', verbose_name='Супербольшой Изображений'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/thumbnail', verbose_name='Миниатюра Изображений'),
        ),
        migrations.AddField(
            model_name='products',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='products',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное Название продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='included_branding',
            field=models.JSONField(blank=True, null=True, verbose_name='Включенный брендинг'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
