# Generated by Django 5.0.4 on 2024-05-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategories', verbose_name='Категория продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
