# Generated by Django 5.0.4 on 2024-06-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='image',
        ),
        migrations.AddField(
            model_name='colors',
            name='hex',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
