# Generated by Django 5.0.2 on 2024-04-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='big',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='big_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='small',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='small_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='superbig',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='superbig_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='products',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='included_branding',
        ),
        migrations.AddField(
            model_name='productimage',
            name='colorID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.colors', verbose_name='Цвета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='изображения'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL изображения'),
        ),
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Штрих-код продукта'),
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, default='S-XXL', max_length=155, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='products',
            name='moq',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ondemand',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pack',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.CharField(blank=True, default='S-XXL', max_length=155, null=True, verbose_name='Размер товара'),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='Категория значка'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Категория логотипа'),
        ),
        migrations.CreateModel(
            name='ExternalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_categories', to='product.productcategories')),
            ],
            options={
                'verbose_name': 'Site Category',
                'verbose_name_plural': 'Site Categories ',
                'db_table': 'product_site_category',
                'unique_together': {('external_id',)},
            },
        ),
    ]
