# Generated by Django 5.0.2 on 2024-03-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_color_remove_productimage_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='vendor_code',
            new_name='article',
        ),
    ]
