# Generated by Django 5.0.2 on 2024-03-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_categoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='tertiary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TertiaryCategoryID', to='product.productcategories'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CategoryID', to='product.productcategories'),
        ),
    ]
