# Generated by Django 5.0.2 on 2024-04-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_big_remove_productimage_big_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalcategory',
            unique_together={('external_id', 'category')},
        ),
    ]
