# Generated by Django 5.0.4 on 2024-06-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_colorid'),
    ]

    operations = [

    ]
