# Generated by Django 5.0.4 on 2024-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_categoryid_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступен на сайте?'),
        ),
    ]
