# Generated by Django 5.0.4 on 2024-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategories_description_productcategories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
