# Generated by Django 5.0.2 on 2024-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_vendor_code_products_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='big_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL большого изображения'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='small_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL маленького изображения'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='superbig_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL супербольшого изображения'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL миниатюры изображения'),
        ),
    ]
