# Generated by Django 5.0.4 on 2024-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
