# Generated by Django 5.0.4 on 2024-05-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategories_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.products'),
        ),
    ]
