# Generated by Django 5.0.4 on 2024-06-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sitelogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'ordering': ('-is_available', 'order', 'order_by_site'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AddField(
            model_name='productcategories',
            name='order_by_site',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядок сайта'),
        ),
    ]
