# Generated by Django 5.0.2 on 2024-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategories_tertiary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='is_hits',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_pop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/category/logo/', verbose_name='Logo Category'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='media/category/icon/', verbose_name='Icon Category'),
        ),
    ]
