# Generated by Django 5.0.4 on 2024-06-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sitelogo_alter_productcategories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
