# Generated by Django 5.0.4 on 2024-04-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategories_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcategory',
            options={'verbose_name': 'Категория сайта', 'verbose_name_plural': 'Категории сайта'},
        ),
        migrations.AlterField(
            model_name='externalcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_categories', to='product.productcategories', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='externalcategory',
            name='external_id',
            field=models.CharField(max_length=255, verbose_name='внешний идентификатор'),
        ),
    ]
