# Generated by Django 5.0.2 on 2024-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_externalcategory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='moq',
            field=models.CharField(blank=True, default='0', max_length=256, null=True),
        ),
    ]
