# Generated by Django 5.0.4 on 2024-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
