# Generated by Django 5.0.2 on 2024-03-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcategories_is_hits_productcategories_is_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.productcategories',),
        ),
        migrations.CreateModel(
            name='TertiaryCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Tertiary Category',
                'verbose_name_plural': 'Tertiary Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.productcategories',),
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='is_hits',
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='is_pop',
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='tertiary_category',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Is Hit?'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular?'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productcategories'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is New?'),
        ),
    ]
