# Generated by Django 5.0.4 on 2024-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Описание'),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Заголовок'),
        ),
        migrations.AlterField(
            model_name='products',
            name='common_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
