# Generated by Django 5.0.2 on 2024-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
