# Generated by Django 5.0.2 on 2024-03-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage_big_url_productimage_small_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
