# Generated by Django 5.0.4 on 2024-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_externalcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название продукта'),
        ),
    ]
