# Generated by Django 5.0.2 on 2024-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategories_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'ordering': ['parent__id', 'parent__parent__id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
