# Generated by Django 5.0.2 on 2024-04-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategories_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
