# Generated by Django 5.0.4 on 2024-04-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(max_length=256, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Штрих-код продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(default='S-XXL', max_length=256, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_size',
            field=models.CharField(default='S-XXL', max_length=256, verbose_name='Размер товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Масса'),
        ),
    ]
