# Generated by Django 5.0.2 on 2024-03-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_subcategory_tertiarycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'product_color',
            },
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Is Hit?'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is New?'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main-image'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colorProduct', to='product.colors')),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productID', to='product.products')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
