# Generated by Django 5.0.4 on 2024-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_products_quantity_products_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
