# Generated by Django 5.0.4 on 2024-05-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='parent',
        ),
    ]
