# Generated by Django 5.0.4 on 2024-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_products_article_alter_products_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(max_length=512, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(default='S-XXL', max_length=512, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='products',
            name='moq',
            field=models.CharField(blank=True, default='0', max_length=512, null=True),
        ),
    ]
