# Generated by Django 5.0.4 on 2024-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_added_recently'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='products_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='recently_products_count',
            field=models.IntegerField(default=0),
        ),
    ]
