# Generated by Django 5.0.2 on 2024-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_colors_alter_productcategories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
