# Generated by Django 5.0.4 on 2024-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_added_recently'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='site_logos/')),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logos',
                'db_table': 'site_logos',
            },
        ),
        migrations.AddField(
            model_name='productcategories',
            name='products_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategories',
            name='recently_products_count',
            field=models.IntegerField(default=0),
        ),
    ]
