# Generated by Django 5.0.4 on 2024-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='order_top',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
