# Generated by Django 5.0.4 on 2024-06-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
