# Generated by Django 5.0.2 on 2024-04-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcategories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='product.products')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.set')),
            ],
        ),
        migrations.CreateModel(
            name='SetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/set/')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.setproduct')),
            ],
        ),
    ]
