# Generated by Django 5.0.4 on 2024-05-03 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_products_article_alter_products_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategories',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
