# Generated by Django 5.0.4 on 2024-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_sitelogo_productcategories_products_count_and_more'),
    ]

    operations = []
