# Generated by Django 5.0.2 on 2024-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_products_brand_products_height_products_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
