# Generated by Django 5.0.2 on 2024-04-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcategories_order'),
        ('product', '0007_set_setproduct_setimage'),
    ]

    operations = [
    ]
