# Generated by Django 5.0.4 on 2024-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_sitelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='externalcategory',
            name='external_id',
            field=models.CharField(max_length=500, verbose_name='внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=550, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Заголовок'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='common_name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
