# Generated by Django 5.0.4 on 2024-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_colors_name_alter_externalcategory_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='discounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
