# Generated by Django 5.0.2 on 2024-04-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_setproduct_set_remove_setimage_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='productID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='product.products', verbose_name='Код товара'),
        ),
    ]
