# Generated by Django 5.0.2 on 2024-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productimage_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен на сайте?'),
        ),
    ]
