# Generated by Django 5.0.4 on 2024-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_sitelogo_productcategories_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('subtitle', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='product-banners/')),
                ('button_title', models.CharField(max_length=128)),
                ('button_url', models.URLField()),
            ],
            options={
                'verbose_name': 'product banner',
                'verbose_name_plural': 'product banners',
                'db_table': 'product_banners',
            },
        ),
    ]
