# Generated by Django 5.0.4 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_products_article_alter_products_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
