# Generated by Django 5.0.4 on 2024-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productbanner_sitelogo'),
    ]

    operations = []
