# Generated by Django 5.0.2 on 2024-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productcategories_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
