# Generated by Django 5.0.4 on 2024-05-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_products_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'ordering': ('-is_available', 'order'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
