# Generated by Django 5.0.2 on 2024-04-16 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productcategories_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(default='Category Maldex', max_length=150, verbose_name='Название категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(default='9D9SF3', max_length=155, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 4, 16, 18, 22, 49, 67064), verbose_name='Данные опубликованы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='Description Maldex', verbose_name='Описания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(default='S-XXL', max_length=155, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='Product Maldex', max_length=150, verbose_name='Название продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='ondemand',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], default='RUB', max_length=10, verbose_name='Цена валюта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_size',
            field=models.CharField(default='S-XXL', max_length=155, verbose_name='Размер товара'),
        ),
    ]
