# Generated by Django 5.0.4 on 2024-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productcategories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
