# Generated by Django 5.0.4 on 2024-05-09 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productcategories_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'фильтр для продукта',
                'verbose_name_plural': 'фильтры для продукта',
                'db_table': 'filter_for_product',
            },
        ),
        migrations.CreateModel(
            name='ProductFilterProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productfiltermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
            options={
                'verbose_name': 'фильтрует продукты по продукту',
                'verbose_name_plural': 'фильтрует продукты по продукту',
                'db_table': 'filter_for_product_products',
            },
        ),
    ]
