# Generated by Django 5.0.4 on 2024-05-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productfiltermodel_productfilterproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilterproducts',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productfiltermodel'),
        ),
    ]
