# Generated by Django 5.0.4 on 2024-05-09 13:18

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='описание')),
                ('type', models.CharField(choices=[('home', 'home'), ('other', 'other')], max_length=10, verbose_name='тип')),
                ('order', models.PositiveSmallIntegerField(blank=True, verbose_name='очередь')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'faq',
                'ordering': ('type', 'order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='LinkTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
            ],
            options={
                'db_table': 'link_tag_category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'project',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.linktagcategory')),
            ],
            options={
                'db_table': 'link_tag',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PrintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='print-categories/', verbose_name='изображение')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='содержание')),
                ('requirement', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='требование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.printcategory', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'Категория печати',
                'verbose_name_plural': 'Категории печати',
                'db_table': 'print_category',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='blog.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
                'db_table': 'project_image',
                'ordering': ('project',),
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='product.products', verbose_name='продукт')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Продукт проекта',
                'verbose_name_plural': 'Продукты проекта',
                'db_table': 'project_product',
                'ordering': ('project', 'product'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип содержимого')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'db_table': 'blog_tag',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', verbose_name='теги проекта'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='содержание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='image')),
                ('tags', models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='теги статей')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
                'ordering': ('-pub_date', 'title'),
            },
        ),
    ]
