# Generated by Django 5.0.4 on 2024-08-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_printcategory_discounts_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcategory',
            name='image',
        ),
        migrations.CreateModel(
            name='PrintCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='print-categories/', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.printcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Изображение категории печати',
                'verbose_name_plural': 'Изображения категории печати',
                'db_table': 'print_category_image',
                'ordering': ('category',),
            },
        ),
    ]
