# Generated by Django 5.0.2 on 2024-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
