# Generated by Django 5.0.4 on 2024-04-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
