# Generated by Django 5.0.2 on 2024-04-16 12:13

import ckeditor.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_printcategory_requirement_article_project'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printcategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='print-categories/'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='requirement',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
