# Generated by Django 5.0.4 on 2024-04-25 05:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_projectimage_project'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0004_alter_externalcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pub_date', 'title'), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('type', 'order', 'title'), 'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='printcategory',
            options={'ordering': ('title',), 'verbose_name': 'Категория печати', 'verbose_name_plural': 'Категории печати'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('project',), 'verbose_name': 'Изображение проекта', 'verbose_name_plural': 'Изображения проекта'},
        ),
        migrations.AlterModelOptions(
            name='projectproduct',
            options={'ordering': ('project', 'product'), 'verbose_name': 'Продукт проекта', 'verbose_name_plural': 'Продукты проекта'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='теги статей'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='очередь'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('home', 'home'), ('other', 'other')], max_length=10, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='print-categories/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.printcategory', verbose_name='родительская категория'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='requirement',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='требование'),
        ),
        migrations.AlterField(
            model_name='printcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', verbose_name='теги проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='blog.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='product.products', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
        migrations.AlterModelTable(
            name='printcategory',
            table='print_category',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_image',
        ),
        migrations.AlterModelTable(
            name='projectproduct',
            table='project_product',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='blog_tag',
        ),
    ]
