# Generated by Django 5.0.4 on 2024-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_image_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'link_tag',
                'ordering': ('order',),
            },
        ),
    ]
