# Generated by Django 5.0.4 on 2024-05-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_linktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
            ],
            options={
                'db_table': 'link_tag_category',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='linktag',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.linktagcategory'),
            preserve_default=False,
        ),
    ]
