# Generated by Django 5.0.2 on 2024-02-26 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name city')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Short name')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data updated')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'user_city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name Country')),
                ('short_name', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Short name')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data updated')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'user_country',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('icon', models.ImageField(upload_to='path/', verbose_name='Icon Social Media')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data created')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'user_social_media',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=18, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('photo', models.ImageField(upload_to='path/', verbose_name='Avatar')),
                ('about', models.TextField(blank=True, default='', null=True, verbose_name='About yourself')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is activate')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data created')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='City', to='auth_app.city')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'Users',
                'db_table': 'user_table',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(auto_created='Country', blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.country'),
        ),
        migrations.CreateModel(
            name='SocialThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data updated')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Data created')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialThrough', to='auth_app.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SocialThroughUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Through',
                'verbose_name_plural': 'Social Through',
                'db_table': 'user_social_through',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_media',
            field=models.ManyToManyField(related_name='socialLinks', through='auth_app.SocialThrough', to='auth_app.socialmedia'),
        ),
        migrations.CreateModel(
            name='UserLastLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoginHistory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Last Login User',
                'verbose_name_plural': 'Last Login Users',
                'db_table': 'user_last_login',
            },
        ),
    ]
