# Generated by Django 5.0.4 on 2024-04-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='socialthrough',
            name='social',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='socialthrough',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialThrough',
        ),
    ]
