# Generated by Django 5.0.4 on 2024-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_customuser_phone_number_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='user/'),
            preserve_default=False,
        ),
    ]
