# Generated by Django 5.0.4 on 2024-05-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='banner.banner')),
            ],
        ),
    ]
