# Generated by Django 5.0.2 on 2024-03-10 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
        ('product', '0003_productcategories_tertiary_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Name of Banner Carousel')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Carousel',
                'verbose_name_plural': 'Banner Carousel',
                'db_table': 'banner_carousel',
            },
        ),
        migrations.CreateModel(
            name='BannerCarouselProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('bannerCarouselID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerCarouselID', to='banner.bannercarousel')),
                ('productCarouselID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerCarouselProduct', to='product.products')),
            ],
        ),
    ]
