# Generated by Django 5.0.4 on 2024-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannercarousel',
            old_name='video',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='banner_carousel/'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
