# Generated by Django 5.0.2 on 2024-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Banner Maldex', max_length=155, verbose_name='Название баннера'),
            preserve_default=False,
        ),
    ]
