# Generated by Django 5.0.4 on 2024-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order_by_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
