# Generated by Django 5.0.4 on 2024-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_bannercarousel_video_bannercarousel_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='bannerproduct',
            name='custom_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='bannerproduct',
            old_name='custom_id',
            new_name='id',
        )
    ]
