# Generated by Django 5.0.4 on 2024-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_order_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order_by_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Order By ID'),
        ),
    ]
