# Generated by Django 5.0.2 on 2024-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_bannercarousel_bannercarouselproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarouselproduct',
            name='bannerCarouselVideo',
            field=models.FileField(blank=True, null=True, upload_to='media/banner/carousel/video/'),
        ),
    ]
