# Generated by Django 5.0.4 on 2024-05-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='banner',
        ),
        migrations.AddField(
            model_name='button',
            name='banner_carousel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='banner.bannercarousel'),
            preserve_default=False,
        ),
    ]
