# Generated by Django 5.0.4 on 2024-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_remove_button_banner_button_banner_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercarouselproduct',
            name='bannerCarouselVideo',
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/banner/carousel/video/', verbose_name='Баннер-карусель Видео'),
        ),
    ]
