# Generated by Django 5.0.2 on 2024-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_bannercarouselproduct_bannercarouselvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
