# Generated by Django 5.0.2 on 2024-03-14 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_banner_created_at_and_more'),
        ('product', '0009_alter_colors_options_alter_productcategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterModelOptions(
            name='bannercarousel',
            options={'verbose_name': 'Баннер-карусель', 'verbose_name_plural': 'Баннер-карусель'},
        ),
        migrations.AlterModelOptions(
            name='bannercarouselproduct',
            options={'verbose_name': 'Баннер-карусель Продукт', 'verbose_name_plural': 'Баннер-карусель Продукт'},
        ),
        migrations.AlterModelOptions(
            name='bannerproduct',
            options={'verbose_name': 'Продукт Баннера', 'verbose_name_plural': 'Продукт Баннера'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Название баннера'),
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Название баннерной карусели'),
        ),
        migrations.AlterField(
            model_name='bannercarouselproduct',
            name='bannerCarouselID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerCarouselID', to='banner.bannercarousel', verbose_name='Идентификатор баннерной карусели'),
        ),
        migrations.AlterField(
            model_name='bannercarouselproduct',
            name='bannerCarouselVideo',
            field=models.FileField(blank=True, null=True, upload_to='media/banner/carousel/video/', verbose_name='Баннер-карусель Видео'),
        ),
        migrations.AlterField(
            model_name='bannercarouselproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bannercarouselproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='bannercarouselproduct',
            name='productCarouselID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerCarouselProduct', to='product.products', verbose_name='Идентификатор карусели товаров баннера'),
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='bannerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerID', to='banner.banner', verbose_name='Идентификатор баннера'),
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='productID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bannerProduct', to='product.products', verbose_name='Идентификатор товара'),
        ),
        migrations.AlterModelTable(
            name='bannercarouselproduct',
            table='banner_carousel_product',
        ),
        migrations.AlterModelTable(
            name='bannerproduct',
            table='banner_product',
        ),
    ]
