# Generated by Django 5.0.4 on 2024-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_remove_bannercarouselproduct_bannercarouselvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
