# Generated by Django 5.0.4 on 2024-05-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_alter_button_url'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products'),
        ),
        migrations.DeleteModel(
            name='BannerCarouselProduct',
        ),
    ]
