# Generated by Django 5.0.2 on 2024-04-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftsBaskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
                ('other_sets', models.JSONField(blank=True, null=True, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Данные опубликованы')),
            ],
            options={
                'verbose_name': 'Подарочные наборы',
                'verbose_name_plural': 'Подарочные наборы',
                'db_table': 'gifts_basket',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название категории')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен на сайте?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gifts_baskets.giftsbasketcategory')),
            ],
            options={
                'verbose_name': 'Подарочные наборы Категория',
                'verbose_name_plural': 'Подарочные наборы Категория',
                'db_table': 'gifts_basket_category',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('product_sets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('gift_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='gifts_baskets.giftsbaskets')),
            ],
            options={
                'verbose_name': 'Подарочные наборы товара',
                'verbose_name_plural': 'Подарочные наборы товара',
                'db_table': 'gifts_basket_product',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='gift_basket/', verbose_name='')),
                ('gift_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_images', to='gifts_baskets.giftsbaskets')),
            ],
            options={
                'verbose_name': 'Подарочные наборы изображения',
                'verbose_name_plural': 'Подарочные наборы изображения',
                'db_table': 'gifts_basket_image',
            },
        ),
    ]
