# Generated by Django 5.0.4 on 2024-04-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен на сайте?')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Каталог наборов',
                'verbose_name_plural': 'Каталог наборов',
                'db_table': 'set_category',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название категории')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен на сайте?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gifts_baskets.giftsbasketcategory')),
            ],
            options={
                'verbose_name': 'Подарочные наборы Категория',
                'verbose_name_plural': 'Подарочные наборы Категория',
                'db_table': 'gifts_basket_category',
            },
        ),
        migrations.CreateModel(
            name='GiftsBaskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('small_header', models.TextField(blank=True, null=True, verbose_name='')),
                ('article', models.CharField(blank=True, max_length=155, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, null=True, verbose_name='')),
                ('other_sets', models.JSONField(blank=True, null=True, verbose_name='')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена валюта')),
                ('discount_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена со скидкой')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('gift_basket_category', models.ManyToManyField(blank=True, null=True, related_name='cateGiftBasket', to='gifts_baskets.giftsbasketcategory')),
            ],
            options={
                'verbose_name': 'Подарочные наборы',
                'verbose_name_plural': 'Подарочные наборы',
                'db_table': 'gifts_basket',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('product_sets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('gift_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='gifts_baskets.giftsbaskets')),
            ],
            options={
                'verbose_name': 'Подарочные наборы товара',
                'verbose_name_plural': 'Подарочные наборы товара',
                'db_table': 'gifts_basket_product',
            },
        ),
        migrations.CreateModel(
            name='SetProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('product_sets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('set_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setProducts', to='gifts_baskets.setcategory')),
            ],
            options={
                'verbose_name': 'Наборы Каталог товаров',
                'verbose_name_plural': 'Наборы Каталог товаров',
                'db_table': 'set_product',
            },
        ),
    ]
