# Generated by Django 5.0.2 on 2024-04-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsbaskets',
            name='gift_basket_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='cateGiftBasket', to='gifts_baskets.giftsbasketcategory'),
        ),
    ]
