# Generated by Django 5.0.4 on 2024-04-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен на сайте?')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Каталог наборов',
                'verbose_name_plural': 'Каталог наборов',
                'db_table': 'set_category',
            },
        ),
        migrations.CreateModel(
            name='SetProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('product_sets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='product.products')),
                ('set_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='setProducts', to='gifts_baskets.setcategory')),
            ],
            options={
                'verbose_name': 'Наборы Каталог товаров',
                'verbose_name_plural': 'Наборы Каталог товаров',
                'db_table': 'set_product',
            },
        ),
        migrations.CreateModel(
            name='GiftsBasketImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='gift_basket/')),
                ('gift_basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='basket_images', to='gifts_baskets.giftsbaskets')),
            ],
            options={
                'verbose_name': 'Подарочные наборы изображения',
                'verbose_name_plural': 'Подарочные наборы изображения',
                'db_table': 'gifts_basket_image',
            },
        ),
    ]

