# Generated by Django 5.0.4 on 2024-04-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0002_giftsbasketimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Административные файлы',
                'verbose_name_plural': 'Административные файлы',
                'db_table': 'admin_files',
            },
        ),
    ]
