# Generated by Django 5.0.2 on 2024-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0002_giftsbaskets_gift_basket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsbasketimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='gift_basket/'),
        ),
    ]
