# Generated by Django 5.0.2 on 2024-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0003_adminfiles_giftsbasketimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsbaskets',
            name='gift_basket_category',
            field=models.ManyToManyField(blank=True, related_name='cateGiftBasket', to='gifts_baskets.giftsbasketcategory'),
        ),
    ]
