# Generated by Django 5.0.2 on 2024-04-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0003_alter_giftsbasketimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsbaskets',
            name='article',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='giftsbaskets',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='giftsbaskets',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='giftsbaskets',
            name='price_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена валюта'),
        ),
    ]
