# Generated by Django 5.0.2 on 2024-04-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0004_giftsbaskets_article_giftsbaskets_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsbaskets',
            name='small_header',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
