# Generated by Django 5.0.4 on 2024-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0004_alter_giftsbaskets_gift_basket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='giftsbaskets',
            name='tags',
            field=models.ManyToManyField(related_name='baskets', to='gifts_baskets.tag'),
        ),
    ]
