# Generated by Django 5.0.4 on 2024-04-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0005_tag_giftsbaskets_tags'),
        ('product', '0003_productcategories_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsbasketcategory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название категории подарочной корзины'),
        ),
        migrations.AlterField(
            model_name='giftsbasketimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='gift_basket/', verbose_name='Изображений'),
        ),
        migrations.AlterField(
            model_name='giftsbasketproduct',
            name='product_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Наборы продуктов'),
        ),
        migrations.AlterField(
            model_name='giftsbasketproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='other_sets',
            field=models.JSONField(blank=True, null=True, verbose_name='Другие наборы'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='small_header',
            field=models.TextField(blank=True, null=True, verbose_name='Назовите небольшой заголовок подарочной корзины.'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='tags',
            field=models.ManyToManyField(related_name='baskets', to='gifts_baskets.tag', verbose_name='Бирки для корзины подарков'),
        ),
        migrations.AlterField(
            model_name='giftsbaskets',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подарочной корзины'),
        ),
        migrations.AlterField(
            model_name='setcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='setproducts',
            name='product_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Наборы продуктов'),
        ),
        migrations.AlterField(
            model_name='setproducts',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
