# Generated by Django 5.0.4 on 2024-04-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0006_alter_giftsbasketcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
    ]
