# Generated by Django 5.0.4 on 2024-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0008_tag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
