# Generated by Django 5.0.4 on 2024-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0009_alter_tag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsbaskets',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='baskets', to='gifts_baskets.tag', verbose_name='Бирки для корзины подарков'),
        ),
    ]
