# Generated by Django 5.0.4 on 2024-04-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0010_alter_giftsbaskets_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File'),
        ),
    ]
