# Generated by Django 5.0.4 on 2024-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts_baskets', '0012_tagcategory_alter_tag_name_tag_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsbaskets',
            name='tags',
            field=models.ManyToManyField(related_name='baskets', to='gifts_baskets.tag', verbose_name='Бирки для корзины подарков'),
        ),
    ]
